// Generated by CoffeeScript 1.10.0
(function() {
  var dotests, test;

  test = require('tape');

  dotests = function() {
    return test('timing test', function(t) {
      var start;
      t.plan(2);
      t.equal(typeof Date.now, 'function');
      start = Date.now();
      setTimeout((function() {
        t.equal(Date.now() - start, 100);
      }), 100);
    });
  };

  if (typeof window === "undefined" || window === null) {
    dotests();
  }

}).call(this);
