// Generated by CoffeeScript 1.10.0
(function() {
  var EL, self;

  self = this;

  EL = self.root;

  this.cols = [];

  this.rows = [];

  this.on('update', function() {});

  EL.load = (function(newrows) {
    if (newrows === void 0 || !newrows.length) {
      return;
    }
    self.cols = Object.keys(newrows[0]);
    self.rows = newrows;
    self.update();
  }).bind(this);

  EL.append = (function(newrows) {
    self.rows.push(newrows);
    self.update();
  }).bind(this);

  EL.reset = function() {
    self.rows = [];
    self.update();
  };

  this.drawcell = (function(rowdata, tr, col) {
    var idx;
    idx = tr.root.children.length;
    if (idx === 0) {
      return;
    }
    if (self.cols[idx - 1].inner) {
      tr.root.children[idx - 1].innerHTML = riot.util.tmpl(self.cols[idx - 1].inner, rowdata);
    } else {
      tr.root.children[idx - 1].innerHTML = rowdata[self.cols[idx - 1].name];
    }
  }).bind(this);

  riot.tag('rcol', '', function(opts) {
    var self;
    self = this;
    this.on('mount', function() {
      self.root.style.display = 'none';
    });
  });

}).call(this);
